# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-23 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='phone',
        ),
    ]
