# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190223_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='latitude',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='longitude',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
