# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190304_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='longitude',
        ),
    ]
